#!/bin/sh
# entrypoint.sh — dnsmasq authoritative DNS server for the OTForge
#
# Generates a dnsmasq zone configuration at runtime from environment variables,
# then starts dnsmasq in foreground mode so Docker captures all output.
#
# Every DNS query is logged to stdout — students can observe reconnaissance
# in real time with:  docker logs -f <container_name>
#
# Environment variables:
#   DNS_DOMAIN      Authoritative domain to serve (default: meridian-process.com)
#   WEB_SERVER_IP   A record for apex + www + remote  (default: 203.0.113.10)
#   DNS_UPSTREAM    Upstream resolver for non-local names  (default: 8.8.8.8)
#                   Set to "" for fully air-gapped operation.
#
# NOTE on dnsmasq address= vs host-record=:
#   address=/example.com/IP  matches the apex AND all *.example.com subdomains
#   (wildcard catch-all — not what we want here).
#   host-record=example.com,IP  creates an exact A record for the apex only.
#   We use host-record for the apex and address=/sub.example.com/IP for each
#   specific subdomain so that unlisted names (ot, scada, plc, hmi) return
#   NXDOMAIN — which is the intended behaviour for the DNS enumeration exercise.

set -e

DNS_DOMAIN="${DNS_DOMAIN:-meridian-process.com}"
WEB_SERVER_IP="${WEB_SERVER_IP:-203.0.113.10}"
# MAIL_SERVER_IP defaults to WEB_SERVER_IP when not injected by the compose
# generator.  The compose generator auto-injects the claimed email-server IP
# whenever an email-server device is present in the scenario.
MAIL_SERVER_IP="${MAIL_SERVER_IP:-${WEB_SERVER_IP}}"
# Use ${VAR-default} (not ${VAR:-default}) so that DNS_UPSTREAM="" (empty string,
# injected by the compose generator for air-gapped scenarios) is respected.
# With :- the shell replaces even an empty value with the default.
DNS_UPSTREAM="${DNS_UPSTREAM-8.8.8.8}"

echo "[otforge-dns] ================================================"
echo "[otforge-dns] Domain:      ${DNS_DOMAIN}"
echo "[otforge-dns] Web server:  ${WEB_SERVER_IP}"
echo "[otforge-dns] Mail server: ${MAIL_SERVER_IP}"
if [ -n "${DNS_UPSTREAM}" ]; then
    echo "[otforge-dns] Upstream:    ${DNS_UPSTREAM}"
else
    echo "[otforge-dns] Upstream:    <none — air-gapped mode>"
fi
echo "[otforge-dns] ================================================"
echo ""

# Write the zone configuration into /tmp (world-writable in Alpine containers)
cat > /tmp/dnsmasq.conf <<DNSCONF
# dnsmasq configuration — generated by entrypoint.sh
# Authoritative zone: ${DNS_DOMAIN}

# No /etc/hosts — all records come from this file only
no-hosts

# Disable DHCP (DNS-only server)
no-dhcp-interface=

# Log every query to stdout (captured by Docker, viewable with 'docker logs')
log-queries
log-facility=-

# Only respond authoritatively for our domain; forward everything else
local=/${DNS_DOMAIN}/
domain=${DNS_DOMAIN}

# ── A Records ──────────────────────────────────────────────────────────────────
# Apex — host-record creates an exact A record for the bare domain only.
# Do NOT use address=/${DNS_DOMAIN}/IP here: that acts as a wildcard and
# returns the IP for every *.${DNS_DOMAIN} query, breaking the enumeration
# exercise by making non-existent names like ot/scada/plc appear to resolve.
host-record=${DNS_DOMAIN},${WEB_SERVER_IP}

# Specific subdomains — www and remote resolve to the internet-facing web server.
# mail resolves to the mail server (may be the same host as www when MAIL_SERVER_IP
# was not set explicitly — the compose generator injects a separate IP when an
# email-server device is present in the scenario).
# vpn/ot/scada/plc/hmi all return NXDOMAIN — the OT network is reachable only
# because of the firewall misconfiguration, not because it is advertised in DNS.
address=/www.${DNS_DOMAIN}/${WEB_SERVER_IP}
address=/remote.${DNS_DOMAIN}/${WEB_SERVER_IP}
address=/mail.${DNS_DOMAIN}/${MAIL_SERVER_IP}

# MX record — mail exchange for the domain pointing at mail.${DNS_DOMAIN}
# Priority 10 is the standard single-server priority (lower = higher priority).
mx-host=${DNS_DOMAIN},mail.${DNS_DOMAIN},10
DNSCONF

# Add upstream resolver unless air-gapped mode is requested
if [ -n "${DNS_UPSTREAM}" ]; then
    echo "server=${DNS_UPSTREAM}" >> /tmp/dnsmasq.conf
fi

echo "[otforge-dns] Zone records:"
grep "^address=" /tmp/dnsmasq.conf | while IFS= read -r line; do
    echo "[otforge-dns]   ${line}"
done
grep "^mx-host=" /tmp/dnsmasq.conf | while IFS= read -r line; do
    echo "[otforge-dns]   ${line}"
done
echo ""
echo "[otforge-dns] Listening on port 53 (UDP + TCP)..."
echo "[otforge-dns] Queries will appear below:"
echo ""

# --no-daemon  run in foreground so Docker captures stdout/stderr
# --user=root  required inside Docker (no 'dnsmasq' user in Alpine by default)
# -C           use our generated config file
exec dnsmasq --no-daemon --user=root -C /tmp/dnsmasq.conf
