#!/bin/sh
# entrypoint.sh — dnsmasq authoritative DNS server for the OTForge
#
# Generates a dnsmasq zone configuration at runtime from environment variables,
# then starts dnsmasq in foreground mode so Docker captures all output.
#
# Every DNS query is logged to stdout — students can observe reconnaissance
# in real time with:  docker logs -f <container_name>
#
# Environment variables:
#   DNS_DOMAIN      Authoritative domain to serve (default: meridian-process.com)
#   WEB_SERVER_IP   A record for apex + www + remote + vpn  (default: 203.0.113.10)
#   MAIL_SERVER_IP  A record for mail  (default: same as WEB_SERVER_IP)
#   DNS_UPSTREAM    Upstream resolver for non-local names  (default: 8.8.8.8)
#                   Set to "" for fully air-gapped operation.

set -e

DNS_DOMAIN="${DNS_DOMAIN:-meridian-process.com}"
WEB_SERVER_IP="${WEB_SERVER_IP:-203.0.113.10}"
MAIL_SERVER_IP="${MAIL_SERVER_IP:-${WEB_SERVER_IP}}"
DNS_UPSTREAM="${DNS_UPSTREAM:-8.8.8.8}"

echo "[ics-dns] ================================================"
echo "[ics-dns] Domain:      ${DNS_DOMAIN}"
echo "[ics-dns] Web server:  ${WEB_SERVER_IP}"
echo "[ics-dns] Mail server: ${MAIL_SERVER_IP}"
if [ -n "${DNS_UPSTREAM}" ]; then
    echo "[ics-dns] Upstream:    ${DNS_UPSTREAM}"
else
    echo "[ics-dns] Upstream:    <none — air-gapped mode>"
fi
echo "[ics-dns] ================================================"
echo ""

# Write the zone configuration into /tmp (world-writable in Alpine containers)
cat > /tmp/dnsmasq.conf <<DNSCONF
# dnsmasq configuration — generated by entrypoint.sh
# Authoritative zone: ${DNS_DOMAIN}

# No /etc/hosts — all records come from this file only
no-hosts

# Disable DHCP (DNS-only server)
no-dhcp-interface=

# Log every query to stdout (captured by Docker, viewable with 'docker logs')
log-queries
log-facility=-

# Only respond authoritatively for our domain; forward everything else
local=/${DNS_DOMAIN}/
domain=${DNS_DOMAIN}

# ── A Records ──────────────────────────────────────────────────────────────────
# Apex and www → company web server
address=/${DNS_DOMAIN}/${WEB_SERVER_IP}
address=/www.${DNS_DOMAIN}/${WEB_SERVER_IP}

# Remote access portal (same host as www in this deployment)
address=/remote.${DNS_DOMAIN}/${WEB_SERVER_IP}

# VPN gateway (resolves to the same IP in the tutorial scenario)
address=/vpn.${DNS_DOMAIN}/${WEB_SERVER_IP}

# Mail server
address=/mail.${DNS_DOMAIN}/${MAIL_SERVER_IP}
DNSCONF

# Add upstream resolver unless air-gapped mode is requested
if [ -n "${DNS_UPSTREAM}" ]; then
    echo "server=${DNS_UPSTREAM}" >> /tmp/dnsmasq.conf
fi

echo "[ics-dns] Zone records:"
grep "^address=" /tmp/dnsmasq.conf | while IFS= read -r line; do
    echo "[ics-dns]   ${line}"
done
echo ""
echo "[ics-dns] Listening on port 53 (UDP + TCP)..."
echo "[ics-dns] Queries will appear below:"
echo ""

# --no-daemon  run in foreground so Docker captures stdout/stderr
# --user=root  required inside Docker (no 'dnsmasq' user in Alpine by default)
# -C           use our generated config file
exec dnsmasq --no-daemon --user=root -C /tmp/dnsmasq.conf
