#!/bin/sh
# entrypoint.sh — dnsmasq authoritative DNS server for the OTForge
#
# Generates a dnsmasq zone configuration at runtime from environment variables,
# then starts dnsmasq in foreground mode so Docker captures all output.
#
# Every DNS query is logged to stdout — students can observe reconnaissance
# in real time with:  docker logs -f <container_name>
#
# Environment variables:
#   DNS_DOMAIN      Authoritative domain to serve (default: meridian-process.com)
#   WEB_SERVER_IP   A record for apex + www + remote  (default: 203.0.113.10)
#   DNS_UPSTREAM    Upstream resolver for non-local names  (default: 8.8.8.8)
#                   Set to "" for fully air-gapped operation.
#
# NOTE on dnsmasq address= vs host-record=:
#   address=/example.com/IP  matches the apex AND all *.example.com subdomains
#   (wildcard catch-all — not what we want here).
#   host-record=example.com,IP  creates an exact A record for the apex only.
#   We use host-record for the apex and address=/sub.example.com/IP for each
#   specific subdomain so that unlisted names (ot, scada, plc, hmi) return
#   NXDOMAIN — which is the intended behaviour for the DNS enumeration exercise.

set -e

DNS_DOMAIN="${DNS_DOMAIN:-meridian-process.com}"
WEB_SERVER_IP="${WEB_SERVER_IP:-203.0.113.10}"
# Use ${VAR-default} (not ${VAR:-default}) so that DNS_UPSTREAM="" (empty string,
# injected by the compose generator for air-gapped scenarios) is respected.
# With :- the shell replaces even an empty value with the default.
DNS_UPSTREAM="${DNS_UPSTREAM-8.8.8.8}"

echo "[otforge-dns] ================================================"
echo "[otforge-dns] Domain:      ${DNS_DOMAIN}"
echo "[otforge-dns] Web server:  ${WEB_SERVER_IP}"
if [ -n "${DNS_UPSTREAM}" ]; then
    echo "[otforge-dns] Upstream:    ${DNS_UPSTREAM}"
else
    echo "[otforge-dns] Upstream:    <none — air-gapped mode>"
fi
echo "[otforge-dns] ================================================"
echo ""

# Write the zone configuration into /tmp (world-writable in Alpine containers)
cat > /tmp/dnsmasq.conf <<DNSCONF
# dnsmasq configuration — generated by entrypoint.sh
# Authoritative zone: ${DNS_DOMAIN}

# No /etc/hosts — all records come from this file only
no-hosts

# Disable DHCP (DNS-only server)
no-dhcp-interface=

# Log every query to stdout (captured by Docker, viewable with 'docker logs')
log-queries
log-facility=-

# Only respond authoritatively for our domain; forward everything else
local=/${DNS_DOMAIN}/
domain=${DNS_DOMAIN}

# ── A Records ──────────────────────────────────────────────────────────────────
# Apex — host-record creates an exact A record for the bare domain only.
# Do NOT use address=/${DNS_DOMAIN}/IP here: that acts as a wildcard and
# returns the IP for every *.${DNS_DOMAIN} query, breaking the enumeration
# exercise by making non-existent names like ot/scada/plc appear to resolve.
host-record=${DNS_DOMAIN},${WEB_SERVER_IP}

# Specific subdomains — only www and remote resolve (both hosted on the same
# single internet-facing server). vpn/mail/ot/scada/plc/hmi all return NXDOMAIN:
# Meridian uses a cloud mail provider (not in this zone) and has no VPN appliance.
# The OT names are absent from DNS deliberately — the network is reachable only
# because of the firewall misconfiguration, not because it is advertised.
address=/www.${DNS_DOMAIN}/${WEB_SERVER_IP}
address=/remote.${DNS_DOMAIN}/${WEB_SERVER_IP}
DNSCONF

# Add upstream resolver unless air-gapped mode is requested
if [ -n "${DNS_UPSTREAM}" ]; then
    echo "server=${DNS_UPSTREAM}" >> /tmp/dnsmasq.conf
fi

echo "[otforge-dns] Zone records:"
grep "^address=" /tmp/dnsmasq.conf | while IFS= read -r line; do
    echo "[otforge-dns]   ${line}"
done
echo ""
echo "[otforge-dns] Listening on port 53 (UDP + TCP)..."
echo "[otforge-dns] Queries will appear below:"
echo ""

# --no-daemon  run in foreground so Docker captures stdout/stderr
# --user=root  required inside Docker (no 'dnsmasq' user in Alpine by default)
# -C           use our generated config file
exec dnsmasq --no-daemon --user=root -C /tmp/dnsmasq.conf
