#!/bin/bash
# entrypoint.sh — nftables firewall configuration for the ics-sim-firewall container.
#
# This script runs at container start and builds an nftables ruleset from environment
# variables injected by Docker Compose (generated by compose-generator.ts). It then
# keeps the container running so the ruleset stays active.
#
# The firewall container bridges the OT, IT, and DMZ networks (three interfaces),
# which is why NET_ADMIN and NET_RAW capabilities are required in the compose file.
#
# Environment variables:
#   DEVICE_ID          — Device node ID from the scenario (for log identification)
#   FW_DEFAULT_POLICY  — "accept" or "drop" (default: "drop")
#                         drop = deny-by-default (recommended for ICS DMZ)
#                         accept = allow-by-default (useful for open-lab scenarios)
#   FW_OT_TO_IT_PORTS  — Comma-separated TCP port list allowed from OT → IT
#                         e.g., "502,20000" allows Modbus and DNP3 polling from IT
#   FW_IT_TO_OT_PORTS  — Comma-separated TCP port list allowed from IT → OT
#                         e.g., "8080" allows OpenPLC web UI access from IT
#
# Network zones (always 172.20.x.0/24 per ZONE_DEFAULTS in network-config.ts):
#   OT      — 172.20.10.0/24  (PLCs, sensors, field devices)
#   IT      — 172.20.20.0/24  (Historian, HMI, Grafana)
#   DMZ     — 172.20.30.0/24  (Suricata, Zeek — firewall itself)
#   External — 172.20.40.0/24  (Kali attack machine)

set -e

# Read the default policy from env, falling back to "drop" (deny-by-default)
POLICY="${FW_DEFAULT_POLICY:-drop}"

echo "[ics-firewall] Device=${DEVICE_ID}  default-policy=${POLICY}"

# ── Enable IP forwarding ────────────────────────────────────────────────────────
# The firewall container must forward packets between its three network interfaces
# (ot-net, it-net, dmz-net). IP forwarding is disabled by default in the kernel.
# Write to both the global and per-interface sysctl paths; suppress errors if
# running in a restricted kernel environment (some Docker Desktop configurations).
echo 1 > /proc/sys/net/ipv4/ip_forward 2>/dev/null || true
echo 1 > /proc/sys/net/ipv4/conf/all/forwarding 2>/dev/null || true

# ── Initialize nftables ─────────────────────────────────────────────────────────
# Flush any previously loaded ruleset (from a previous container start or hot-reload).
nft flush ruleset

# Create an inet family table — inet matches both IPv4 and IPv6 traffic in one ruleset,
# which simplifies rules compared to having separate ip and ip6 tables.
nft add table inet ics_fw

# ── Forward chain ───────────────────────────────────────────────────────────────
# type filter = packet filtering (not NAT or routing)
# hook forward = matches packets being forwarded between interfaces (not locally terminated)
# priority 0 = standard filter priority
# policy = the action taken when no rule matches (from $POLICY env var)
nft add chain inet ics_fw forward "{ type filter hook forward priority 0; policy ${POLICY}; }"

# ── Stateful rules ──────────────────────────────────────────────────────────────
# Allow established and related connections — this is critical for reply traffic.
# Without this, a TCP response to an allowed request would be dropped on the return path.
nft add rule inet ics_fw forward ct state established,related accept

# Allow ICMP ping between zones for reachability testing (important for exercises).
# Blocking ICMP entirely would make debugging very difficult for students.
nft add rule inet ics_fw forward ip protocol icmp accept
nft add rule inet ics_fw forward ip6 nexthdr icmpv6 accept

# ── OT → IT direction ──────────────────────────────────────────────────────────
# Allow specific TCP ports from OT devices (PLCs, sensors) to IT services (Historian).
# Example: FW_OT_TO_IT_PORTS=502 allows Modbus writes to the historian.
# If the variable is empty or unset, no OT→IT traffic is explicitly permitted.
if [ -n "${FW_OT_TO_IT_PORTS}" ]; then
    for port in $(echo "${FW_OT_TO_IT_PORTS}" | tr ',' ' '); do
        nft add rule inet ics_fw forward \
            ip saddr 172.20.10.0/24 ip daddr 172.20.20.0/24 \
            tcp dport "${port}" accept
        echo "[ics-firewall] Allow OT→IT  port=${port}"
    done
fi

# ── IT → OT direction ──────────────────────────────────────────────────────────
# Allow specific TCP ports from IT hosts (HMI, Grafana) to OT devices (PLCs).
# Example: FW_IT_TO_OT_PORTS=502 allows HMI to poll Modbus registers on PLCs.
# Separating OT→IT from IT→OT lets scenarios model asymmetric trust (OT can
# report to IT but IT cannot initiate control commands to OT).
if [ -n "${FW_IT_TO_OT_PORTS}" ]; then
    for port in $(echo "${FW_IT_TO_OT_PORTS}" | tr ',' ' '); do
        nft add rule inet ics_fw forward \
            ip saddr 172.20.20.0/24 ip daddr 172.20.10.0/24 \
            tcp dport "${port}" accept
        echo "[ics-firewall] Allow IT→OT  port=${port}"
    done
fi

# ── Display final ruleset ───────────────────────────────────────────────────────
# Print the complete ruleset to stdout — visible in `docker logs` for debugging
# and for student exercise verification.
echo "[ics-firewall] nftables ruleset:"
nft list ruleset

# ── Keep container running ──────────────────────────────────────────────────────
# The nftables rules are stateless — they stay active as long as the container
# and its network namespaces are alive. `tail -f /dev/null` keeps the process
# alive without consuming CPU, so the container stays running and rules persist.
exec tail -f /dev/null
