#!/usr/bin/env python3
"""
server.py -- Modbus TCP server + browser-based configuration portal for the
ICS Simulator RTU/sensor device container.

Two servers run concurrently in the same asyncio event loop:

  Port 502  Modbus TCP server (pymodbus 3.7 async API)
            Exposes coils, discrete inputs, holding registers, and input
            registers. Register values drift over time to simulate live
            field measurements.

  Port 80   HTTP configuration portal (asyncio.start_server, no extra deps)
            A session-based web application:
              GET  /         -> redirect to /login (if unauthenticated)
                             -> configuration dashboard (if authenticated)
              GET  /login    -> login form
              POST /login    -> validate credentials, issue session cookie
              GET  /logout   -> clear session, redirect to /login
            Default credentials: admin / admin (overridable via env vars).
            Students type the RTU IP address in Firefox from the engineering
            workstation -- no port number needed because port 80 is the HTTP
            default. Navigating to http://10.200.10.50 brings up the login.

Register map (Modbus TCP):
    HR0  Primary process value (fixed-point x10):
           rtu:   250 -> 25.0 C  (HR1=1013 kPa, HR2=150 L/min -- all drift)
           sensor: 250 -> 25.0 C
           pressure-transmitter: 1013 -> 101.3 kPa
           flow-meter: 150 -> 15.0 L/min
    IR    Mirrors HR so FC4 reads are valid
    DI/CO All zero (writable via Modbus)

Protocol reference: Modbus Application Protocol v1.1b3
pymodbus version: 3.7+ (asyncio API)
"""
import asyncio
import logging
import os
import random
import secrets
import urllib.parse
from datetime import datetime, timezone

from pymodbus.datastore import (
    ModbusSequentialDataBlock,
    ModbusServerContext,
    ModbusSlaveContext,
)
from pymodbus.server import StartAsyncTcpServer

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("ics-modbus")

# ── Device identity (injected by compose-generator.ts) ──────────────────────────
DEVICE_ID    = os.getenv("DEVICE_ID", "device-1")
DEVICE_LABEL = os.getenv("DEVICE_LABEL", "") or os.getenv("DEVICE_ID", "device-1")
CATEGORY     = os.getenv("DEVICE_CATEGORY", "sensor")
PORT         = int(os.getenv("MODBUS_PORT", "502"))
UNIT_ID      = int(os.getenv("MODBUS_UNIT_ID", "1"))

# ── RTU panel configuration (injected when device.rtuConfig is set) ─────────────
RTU_COMM_TYPE = os.getenv("RTU_COMM_TYPE", "")
RTU_PROTOCOL  = os.getenv("RTU_PROTOCOL", "")
RTU_MODE      = os.getenv("RTU_OPERATING_MODE", "")
RTU_POWER     = os.getenv("RTU_POWER_SOURCE", "")
RTU_SITE      = os.getenv("RTU_SITE_TYPE", "")
RTU_POLL_INT  = os.getenv("RTU_POLL_INTERVAL", "")

# ── Web portal credentials (default: admin / admin) ──────────────────────────────
WEB_USER = os.getenv("RTU_WEB_USER", "admin")
WEB_PASS = os.getenv("RTU_WEB_PASS", "admin")
WEB_PORT = 80

# ── In-memory session store ──────────────────────────────────────────────────────
# Tokens are 128-bit hex strings generated by secrets.token_hex().
# The store is cleared on container restart (intentional -- sessions don't persist).
_sessions: set[str] = set()

# ── Modbus datastore reference (set in main()) ───────────────────────────────────
_store: ModbusSlaveContext | None = None

# ── Initial holding register values per device category ──────────────────────────
DEFAULTS: dict[str, list[int]] = {
    "sensor":               [250]  + [0] * 99,
    "pressure-transmitter": [1013] + [0] * 99,
    "flow-meter":           [150]  + [0] * 99,
    "pump":                 [1, 1500] + [0] * 98,
    "valve":                [1000] + [0] * 99,
    "actuator":             [0] * 100,
    "plc":                  [0] * 100,
    "rtu":                  [250, 1013, 150] + [0] * 97,
}

# ── Simulation drift configuration ───────────────────────────────────────────────
DRIFT: dict[str, list[tuple[int, float]]] = {
    "sensor":               [(0, 3.0)],
    "pressure-transmitter": [(0, 1.5)],
    "flow-meter":           [(0, 5.0)],
    "pump":                 [(1, 20.0)],
    "rtu":                  [(0, 5.0), (1, 3.0), (2, 10.0)],
}

# ── Comm-type security notes (mirrors the RTU properties panel) ──────────────────
_SECURITY: dict[str, str] = {
    "cellular":    (
        "Cellular-connected RTUs are often internet-exposed when using a public APN instead "
        "of a private one or VPN tunnel. This is one of the most common misconfigurations "
        "found in pipeline and power-grid ICS assessments."
    ),
    "radio":       (
        "900 MHz licensed-band and ISM-band radio links transmit frames without encryption "
        "or authentication by default. An attacker within radio range can replay or inject "
        "control commands using a software-defined radio (SDR)."
    ),
    "satellite":   (
        "Satellite uplinks (VSAT) introduce 500-1500 ms round-trip latency and often route "
        "outside the corporate security stack, bypassing IDS/SIEM visibility. Jamming the "
        "uplink is a viable physical denial-of-service technique."
    ),
    "mqtt":        (
        "MQTT brokers are commonly cloud-hosted with shared or hardcoded credentials and "
        "wildcard topic ACLs. Any subscriber with the broker address can enumerate all RTU "
        "telemetry topics and inject spoofed sensor readings."
    ),
    "dnp3-serial": (
        "DNP3 over serial (RS-485/232) to a radio or telephone modem is unauthenticated by "
        "default -- DNP3 Secure Authentication v5 exists but is rarely deployed. Physical "
        "access to the serial bus allows frame injection and replay."
    ),
}

# ── Mutable runtime configuration (initialized from env vars, editable via portal) ──
# Students can change these values through the web UI and they take effect immediately
# without restarting the container. Changes are lost when the container restarts.
_config: dict[str, str] = {
    "comm_type": RTU_COMM_TYPE,
    "protocol":  RTU_PROTOCOL,
    "mode":      RTU_MODE,
    "power":     RTU_POWER,
    "site":      RTU_SITE,
    "poll_int":  RTU_POLL_INT,
}

# ── Dropdown options for each editable configuration field ───────────────────────
_COMM_OPTIONS: dict[str, list[tuple[str, str]]] = {
    "comm_type": [
        ("cellular",    "Cellular"),
        ("radio",       "Radio (900 MHz)"),
        ("satellite",   "Satellite (VSAT)"),
        ("mqtt",        "MQTT / Cloud"),
        ("dnp3-serial", "DNP3 Serial"),
    ],
    "protocol": [
        ("modbus",  "Modbus TCP/RTU"),
        ("dnp3",    "DNP3"),
        ("iec104",  "IEC 60870-5-104"),
        ("mqtt",    "MQTT"),
        ("bacnet",  "BACnet"),
    ],
    "mode": [
        ("polled",              "Polled"),
        ("report-by-exception", "Report by Exception (RBE)"),
        ("hybrid",              "Hybrid"),
    ],
    "power": [
        ("solar-battery", "Solar + Battery"),
        ("ac",            "AC Mains"),
        ("battery",       "Battery Only"),
        ("dc",            "DC (24 VDC Instrument)"),
    ],
}

# ── CSS shared between the login and dashboard pages ─────────────────────────────
_BASE_CSS = """
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body {
  background: #0d1117;
  color: #c9d1d9;
  font-family: Arial, Helvetica, sans-serif;
  font-size: 14px;
  min-height: 100vh;
}
a { color: #58a6ff; text-decoration: none; }
a:hover { text-decoration: underline; }
"""


# ══════════════════════════════════════════════════════════════════════════════════
# Modbus datastore + simulation
# ══════════════════════════════════════════════════════════════════════════════════

def build_store() -> ModbusSlaveContext:
    """
    Creates the pymodbus slave context with category-appropriate register values.

    All four data blocks are allocated (DI, CO, HR, IR). IR mirrors HR so both
    FC3 and FC4 reads return consistent values matching real device behaviour.
    """
    hr = list(DEFAULTS.get(CATEGORY, [0] * 100))
    return ModbusSlaveContext(
        di=ModbusSequentialDataBlock(0, [0] * 100),
        co=ModbusSequentialDataBlock(0, [0] * 100),
        hr=ModbusSequentialDataBlock(0, hr),
        ir=ModbusSequentialDataBlock(0, list(hr)),
    )


async def simulate(store: ModbusSlaveContext) -> None:
    """
    Background task: drifts process registers every 2 s to simulate live
    field measurements. Writes to both HR (FC3) and IR (FC4) to keep them
    in sync.
    """
    if CATEGORY not in DRIFT:
        return
    specs = DRIFT[CATEGORY]
    for reg, mag in specs:
        log.info("Simulation: HR%d drifts +/-%.1f per tick", reg, mag)
    while True:
        await asyncio.sleep(2)
        for reg, mag in specs:
            try:
                [val] = store.getValues(3, reg, 1)
                new_val = max(0, min(65535, int(val + random.uniform(-mag, mag))))
                store.setValues(3, reg, [new_val])
                store.setValues(4, reg, [new_val])
            except Exception as exc:
                log.warning("Simulation error (HR%d): %s", reg, exc)


# ══════════════════════════════════════════════════════════════════════════════════
# HTTP portal -- page builders
# ══════════════════════════════════════════════════════════════════════════════════

def _esc(text: str) -> str:
    """Minimal HTML-escape for values inserted into page content."""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


def _select(name: str, options: list[tuple[str, str]], current: str) -> str:
    """Renders an HTML <select> with the current value pre-selected."""
    opts = "".join(
        f'<option value="{_esc(v)}"{" selected" if v == current else ""}>{_esc(label)}</option>'
        for v, label in options
    )
    return f'<select name="{name}" class="cfg-select">{opts}</select>'


def build_login_page(error: bool = False) -> str:
    """
    Renders the RTU configuration portal login screen.

    Shown to any unauthenticated request. The form POSTs credentials to /login.
    If error=True, an 'Invalid credentials' banner is displayed above the form.
    """
    error_html = (
        '<div class="alert">Invalid username or password. Please try again.</div>'
        if error else ""
    )
    label = _esc(DEVICE_LABEL)
    did   = _esc(DEVICE_ID)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login &mdash; RTU Config Portal</title>
  <style>
    {_BASE_CSS}
    body {{
      display: flex;
      justify-content: center;
      align-items: center;
    }}
    .login-wrap {{
      width: 360px;
      padding: 40px 36px;
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 8px;
      text-align: center;
    }}
    .icon {{ font-size: 40px; margin-bottom: 12px; }}
    .device-type {{
      color: #58a6ff;
      font-size: 17px;
      font-weight: bold;
      margin-bottom: 4px;
    }}
    .device-name {{
      color: #8b949e;
      font-size: 13px;
      margin-bottom: 28px;
    }}
    .alert {{
      background: #3d1a1a;
      color: #f85149;
      border: 1px solid #6e3030;
      border-radius: 4px;
      padding: 8px 12px;
      margin-bottom: 18px;
      font-size: 13px;
      text-align: left;
    }}
    label {{
      display: block;
      text-align: left;
      color: #8b949e;
      font-size: 12px;
      margin-bottom: 5px;
    }}
    input[type=text], input[type=password] {{
      width: 100%;
      background: #0d1117;
      border: 1px solid #30363d;
      border-radius: 4px;
      color: #e6edf3;
      padding: 9px 12px;
      font-size: 14px;
      margin-bottom: 14px;
      transition: border-color 0.15s;
    }}
    input:focus {{
      outline: none;
      border-color: #58a6ff;
    }}
    button {{
      width: 100%;
      background: #238636;
      color: #fff;
      border: none;
      border-radius: 4px;
      padding: 10px;
      font-size: 14px;
      font-weight: bold;
      cursor: pointer;
      transition: background 0.15s;
    }}
    button:hover {{ background: #2ea043; }}
    .footer-note {{
      color: #6e7681;
      font-size: 11px;
      margin-top: 20px;
    }}
  </style>
</head>
<body>
  <div class="login-wrap">
    <div class="icon">&#x1F4F6;</div>
    <div class="device-type">Remote Terminal Unit</div>
    <div class="device-name">{label} &mdash; Configuration Portal</div>
    {error_html}
    <form method="POST" action="/login">
      <label for="u">Username</label>
      <input type="text" id="u" name="username" autocomplete="username"
             placeholder="admin" required>
      <label for="p">Password</label>
      <input type="password" id="p" name="password"
             autocomplete="current-password" placeholder="&bull;&bull;&bull;&bull;&bull;" required>
      <button type="submit">Login</button>
    </form>
    <div class="footer-note">Device ID: {did} &nbsp;&bull;&nbsp; Unit: {UNIT_ID}</div>
  </div>
</body>
</html>"""


def build_dashboard_page(saved: bool = False) -> str:
    """
    Renders the authenticated RTU configuration dashboard.

    Device Identity is read-only.  Communication Configuration is an editable
    form — dropdowns for comm type, protocol, operating mode, and power source;
    a text input for site name; a number input for poll interval.  Submitting
    the form POSTs to /config which updates _config in memory and redirects
    back here with ?saved=1 so a success banner can be shown.

    The Register Status section auto-refreshes every 5 seconds.  Because all
    form fields are re-populated from _config on each render, a page refresh
    never discards saved values (only unsaved in-progress edits are lost).
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # Live register values from the Modbus datastore
    hr = _store.getValues(3, 0, 8) if _store else [0] * 8
    ir = _store.getValues(4, 0, 8) if _store else [0] * 8
    co = _store.getValues(1, 0, 8) if _store else [0] * 8
    di = _store.getValues(2, 0, 8) if _store else [0] * 8

    is_rtu = CATEGORY in ("rtu", "iec104-rtu")
    label  = _esc(DEVICE_LABEL)
    did    = _esc(DEVICE_ID)

    # ── Helper: table row ──────────────────────────────────────────────────────
    def tr(field: str, value: str) -> str:
        return f'<tr><td class="f">{_esc(field)}</td><td class="v">{value}</td></tr>'

    def badge(text: str, cls: str = "blue") -> str:
        return f'<span class="badge {cls}">{_esc(text)}</span>'

    # ── Identity rows (read-only) ──────────────────────────────────────────────
    id_rows = (
        tr("Device ID", f"<code>{did}</code>") +
        tr("Display Name", label) +
        tr("Category", badge(CATEGORY)) +
        tr("Modbus Unit ID", str(UNIT_ID)) +
        tr("Modbus Port", str(PORT))
    )

    # ── Saved confirmation banner ──────────────────────────────────────────────
    saved_html = (
        '<div class="alert-success">&#10003; Configuration saved successfully.</div>'
        if saved else ""
    )

    # ── Communication configuration — editable form (any device with comm config) ─
    comm_html = ""
    if _config.get("comm_type"):
        poll_val = _esc(_config.get("poll_int", ""))
        site_val = _esc(_config.get("site", ""))
        comm_html = f"""
      <section class="card">
        <h2>Communication Configuration</h2>
        {saved_html}
        <form method="POST" action="/config">
          <table>
            <tr>
              <td class="f">Comm Type</td>
              <td class="v">{_select("comm_type", _COMM_OPTIONS["comm_type"], _config.get("comm_type", ""))}</td>
            </tr>
            <tr>
              <td class="f">Protocol</td>
              <td class="v">{_select("protocol", _COMM_OPTIONS["protocol"], _config.get("protocol", ""))}</td>
            </tr>
            <tr>
              <td class="f">Operating Mode</td>
              <td class="v">{_select("mode", _COMM_OPTIONS["mode"], _config.get("mode", ""))}</td>
            </tr>
            <tr>
              <td class="f">Power Source</td>
              <td class="v">{_select("power", _COMM_OPTIONS["power"], _config.get("power", ""))}</td>
            </tr>
            <tr>
              <td class="f">Site / Location</td>
              <td class="v"><input type="text" name="site" class="cfg-input"
                value="{site_val}" placeholder="e.g. Pump Station 4"></td>
            </tr>
            <tr>
              <td class="f">Poll Interval (s)</td>
              <td class="v"><input type="number" name="poll_int" class="cfg-input cfg-narrow"
                value="{poll_val}" min="1" max="3600" placeholder="30"></td>
            </tr>
          </table>
          <div class="form-actions">
            <button type="submit" class="save-btn">Save Configuration</button>
          </div>
        </form>
      </section>"""

    # ── Security note — updates live when comm type changes ────────────────────
    sec_html = ""
    note = _SECURITY.get(_config.get("comm_type", ""), "")
    if note:
        sec_html = f"""
      <section class="card warn">
        <h2>&#9888; Security Note</h2>
        <p>{_esc(note)}</p>
      </section>"""

    # ── Register status cells ──────────────────────────────────────────────────
    def reg_row(prefix: str, values: list[int], count: int = 4) -> str:
        cells = "".join(
            f'<div class="reg"><span class="rn">{prefix}{i}</span>'
            f'<span class="rv">{values[i]}</span></div>'
            for i in range(count)
        )
        return cells

    di_co_html = ""
    if is_rtu:
        di_co_html = f"""
        <p class="rlabel">Coils &mdash; FC01 read / FC05 write (digital outputs)</p>
        <div class="regs">{reg_row("DO", co)}</div>
        <p class="rlabel">Discrete Inputs &mdash; FC02 read-only (sensor status)</p>
        <div class="regs">{reg_row("DI", di)}</div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>RTU Config &mdash; {label}</title>
  <style>
    {_BASE_CSS}
    .topbar {{
      background: #161b22;
      border-bottom: 1px solid #30363d;
      padding: 0 24px;
      height: 52px;
      display: flex;
      align-items: center;
      justify-content: space-between;
    }}
    .topbar-left {{ display: flex; align-items: center; gap: 12px; }}
    .topbar-icon {{ font-size: 22px; }}
    .topbar-title {{ color: #58a6ff; font-size: 16px; font-weight: bold; }}
    .topbar-sub {{ color: #8b949e; font-size: 12px; }}
    .online {{ color: #3fb950; font-size: 13px; font-weight: bold; }}
    .topbar-right {{ display: flex; align-items: center; gap: 20px; }}
    .logout-btn {{
      background: none;
      border: 1px solid #30363d;
      color: #8b949e;
      border-radius: 4px;
      padding: 4px 12px;
      font-size: 12px;
      cursor: pointer;
    }}
    .logout-btn:hover {{ border-color: #58a6ff; color: #58a6ff; }}
    main {{
      max-width: 900px;
      margin: 0 auto;
      padding: 24px;
    }}
    .card {{
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 6px;
      padding: 18px 20px;
      margin-bottom: 16px;
    }}
    .card.warn {{
      border-color: #9e6a03;
      background: #161208;
    }}
    h2 {{
      color: #79c0ff;
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin-bottom: 12px;
    }}
    .card.warn h2 {{ color: #e3b341; }}
    .card.warn p {{ color: #c9a227; font-size: 13px; line-height: 1.6; }}
    table {{ width: 100%; border-collapse: collapse; }}
    tr {{ border-bottom: 1px solid #21262d; }}
    tr:last-child {{ border-bottom: none; }}
    td {{ padding: 7px 4px; font-size: 13px; vertical-align: middle; }}
    td.f {{ color: #8b949e; width: 38%; }}
    td.v {{ color: #e6edf3; }}
    code {{ background: #0d1117; border: 1px solid #30363d; border-radius: 3px;
            padding: 1px 6px; font-family: monospace; font-size: 12px; }}
    .badge {{
      display: inline-block;
      padding: 2px 10px;
      border-radius: 10px;
      font-size: 11px;
      font-weight: bold;
    }}
    .badge.blue  {{ background: #1f6feb; color: #fff; }}
    .badge.green {{ background: #238636; color: #fff; }}
    .regs {{ display: flex; flex-wrap: wrap; gap: 8px; margin-top: 8px; }}
    .reg {{
      background: #0d1117;
      border: 1px solid #30363d;
      border-radius: 4px;
      padding: 6px 12px;
      min-width: 68px;
      text-align: center;
    }}
    .rn {{ font-size: 10px; color: #8b949e; display: block; margin-bottom: 2px; }}
    .rv {{ font-size: 16px; color: #7ee787; display: block; font-weight: bold; }}
    .rlabel {{
      font-size: 11px;
      color: #8b949e;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin: 14px 0 6px;
    }}
    .alert-success {{
      background: #0d2011;
      color: #3fb950;
      border: 1px solid #238636;
      border-radius: 4px;
      padding: 8px 12px;
      margin-bottom: 14px;
      font-size: 13px;
    }}
    .cfg-select {{
      background: #0d1117;
      border: 1px solid #30363d;
      border-radius: 4px;
      color: #e6edf3;
      padding: 5px 8px;
      font-size: 13px;
      cursor: pointer;
    }}
    .cfg-select:focus {{ outline: none; border-color: #58a6ff; }}
    .cfg-input {{
      background: #0d1117;
      border: 1px solid #30363d;
      border-radius: 4px;
      color: #e6edf3;
      padding: 5px 8px;
      font-size: 13px;
      width: 100%;
    }}
    .cfg-input:focus {{ outline: none; border-color: #58a6ff; }}
    .cfg-narrow {{ width: 90px; }}
    .form-actions {{ margin-top: 14px; text-align: right; }}
    .save-btn {{
      background: #238636;
      color: #fff;
      border: none;
      border-radius: 4px;
      padding: 7px 20px;
      font-size: 13px;
      font-weight: bold;
      cursor: pointer;
    }}
    .save-btn:hover {{ background: #2ea043; }}
    footer {{
      color: #6e7681;
      font-size: 11px;
      text-align: center;
      border-top: 1px solid #21262d;
      padding: 12px 0;
      margin-top: 8px;
    }}
  </style>
</head>
<body>
  <div class="topbar">
    <div class="topbar-left">
      <span class="topbar-icon">&#x1F4F6;</span>
      <div>
        <div class="topbar-title">{label}</div>
        <div class="topbar-sub">Remote Terminal Unit &mdash; Configuration Portal</div>
      </div>
    </div>
    <div class="topbar-right">
      <span class="online">&#x25CF; ONLINE</span>
      <a href="/logout"><button class="logout-btn">Logout</button></a>
    </div>
  </div>

  <main>
    <section class="card">
      <h2>Device Identity</h2>
      <table>{id_rows}</table>
    </section>

    {comm_html}

    {sec_html}

    <section class="card">
      <h2>Register Status &mdash; auto-refresh every 5 s</h2>
      <p class="rlabel">Holding Registers &mdash; FC03 read / FC06 write (setpoints)</p>
      <div class="regs">{reg_row("HR", hr)}</div>
      <p class="rlabel">Input Registers &mdash; FC04 read-only (measurements)</p>
      <div class="regs">{reg_row("IR", ir)}</div>
      {di_co_html}
    </section>

    <footer>
      OTForge ICS Simulator &nbsp;&bull;&nbsp; {ts}
    </footer>
  </main>
</body>
</html>"""


# ══════════════════════════════════════════════════════════════════════════════════
# HTTP portal -- request handling
# ══════════════════════════════════════════════════════════════════════════════════

def _parse_request(raw: bytes) -> tuple[str, str, str, dict[str, str], str]:
    """
    Parses the essential fields from a raw HTTP request.

    Returns:
        (method, path, qs, cookies, body)
        method  -- 'GET', 'POST', etc.
        path    -- URL path without query string (e.g. '/login')
        qs      -- raw query string without leading '?' (e.g. 'saved=1'), or ''
        cookies -- dict of cookie name -> value from the Cookie header
        body    -- decoded request body (form data for POST /login)
    """
    # Split HTTP headers from body at the blank line
    try:
        sep = raw.index(b"\r\n\r\n")
        headers_bytes = raw[:sep]
        body = raw[sep + 4:].decode("utf-8", errors="replace")
    except ValueError:
        headers_bytes = raw
        body = ""

    lines = headers_bytes.split(b"\r\n")

    # Request line: "METHOD /path HTTP/1.x"
    req_parts = lines[0].decode("utf-8", errors="replace").split(" ")
    method = req_parts[0].upper() if req_parts else "GET"
    raw_path = req_parts[1] if len(req_parts) >= 2 else "/"
    qs = raw_path.split("?", 1)[1] if "?" in raw_path else ""
    path = raw_path.split("?")[0]

    # Parse Cookie header
    cookies: dict[str, str] = {}
    for line in lines[1:]:
        if line.lower().startswith(b"cookie:"):
            cookie_str = line[7:].strip().decode("utf-8", errors="replace")
            for pair in cookie_str.split(";"):
                if "=" in pair:
                    k, v = pair.strip().split("=", 1)
                    cookies[k.strip()] = v.strip()

    return method, path, qs, cookies, body


def _write_response(writer: asyncio.StreamWriter,
                    status: str,
                    content_type: str,
                    body: bytes,
                    extra: str = "") -> None:
    """Writes a complete HTTP response to the stream writer."""
    header = (
        f"HTTP/1.1 {status}\r\n"
        f"Content-Type: {content_type}\r\n"
        f"Content-Length: {len(body)}\r\n"
        f"Connection: close\r\n"
        f"{extra}"
        f"\r\n"
    ).encode("utf-8")
    writer.write(header + body)


async def http_handler(reader: asyncio.StreamReader,
                       writer: asyncio.StreamWriter) -> None:
    """
    Handles a single incoming HTTP connection for the RTU configuration portal.

    Routing:
      GET  /            authenticated  -> dashboard (saved=True if qs contains saved=1)
      GET  /            anonymous      -> redirect to /login
      GET  /login       any            -> login form
      POST /login       any            -> validate; set cookie + redirect or show error
      GET  /logout      any            -> clear cookie + redirect to /login
      POST /config      authenticated  -> update _config, redirect to /?saved=1
      GET  /favicon.ico any            -> 404 (suppresses browser log noise)
      anything else     any            -> 404

    Session tokens are stored in the module-level _sessions set. Tokens survive
    for the lifetime of the container process (cleared on restart).
    """
    try:
        raw = await asyncio.wait_for(reader.read(8192), timeout=5.0)
        method, path, qs, cookies, body = _parse_request(raw)
        authenticated = cookies.get("sid", "") in _sessions

        # ── /favicon.ico ──────────────────────────────────────────────────────
        if path == "/favicon.ico":
            _write_response(writer, "404 Not Found", "text/plain", b"")

        # ── POST /login ───────────────────────────────────────────────────────
        elif method == "POST" and path == "/login":
            form = dict(urllib.parse.parse_qsl(body))
            username = form.get("username", "")
            password = form.get("password", "")
            if username == WEB_USER and password == WEB_PASS:
                token = secrets.token_hex(16)
                _sessions.add(token)
                log.info("HTTP: login success for user '%s' -- session %s", username, token[:8])
                cookie_header = f"Set-Cookie: sid={token}; HttpOnly; Path=/\r\n"
                _write_response(
                    writer, "302 Found", "text/plain", b"",
                    extra=f"Location: /\r\n{cookie_header}"
                )
            else:
                log.warning("HTTP: failed login attempt for user '%s'", username)
                html = build_login_page(error=True)
                _write_response(writer, "200 OK", "text/html; charset=utf-8", html.encode())

        # ── GET /logout ───────────────────────────────────────────────────────
        elif path == "/logout":
            sid = cookies.get("sid", "")
            _sessions.discard(sid)
            # Expire the cookie by setting Max-Age=0
            clear_cookie = "Set-Cookie: sid=; HttpOnly; Path=/; Max-Age=0\r\n"
            _write_response(
                writer, "302 Found", "text/plain", b"",
                extra=f"Location: /login\r\n{clear_cookie}"
            )

        # ── GET /login (or any unauthenticated request) ───────────────────────
        elif path == "/login" or not authenticated:
            html = build_login_page()
            _write_response(writer, "200 OK", "text/html; charset=utf-8", html.encode())

        # ── POST /config -- save runtime configuration changes ────────────────
        elif method == "POST" and path == "/config" and authenticated:
            form = dict(urllib.parse.parse_qsl(body))
            for key in ("comm_type", "protocol", "mode", "power", "site", "poll_int"):
                if key in form:
                    _config[key] = form[key]
            log.info("HTTP: RTU config updated: %s", _config)
            _write_response(
                writer, "302 Found", "text/plain", b"",
                extra="Location: /?saved=1\r\n"
            )

        # ── GET / -- authenticated dashboard ──────────────────────────────────
        elif path == "/" or path == "":
            html = build_dashboard_page(saved=(qs == "saved=1"))
            _write_response(writer, "200 OK", "text/html; charset=utf-8", html.encode())

        # ── Anything else ─────────────────────────────────────────────────────
        else:
            _write_response(writer, "404 Not Found", "text/plain", b"Page not found")

        await writer.drain()

    except Exception:
        pass
    finally:
        try:
            writer.close()
            await writer.wait_closed()
        except Exception:
            pass


# ══════════════════════════════════════════════════════════════════════════════════
# Main entry point
# ══════════════════════════════════════════════════════════════════════════════════

async def main() -> None:
    """
    Starts both servers and the simulation task in a single asyncio event loop.

    Startup order:
      1. Build the Modbus datastore and set the module-level _store reference.
      2. Start the HTTP configuration portal on port 80 (background task).
      3. Start the register drift simulation (background task).
      4. Start the Modbus TCP server on port 502 (blocks until shutdown).
    """
    global _store

    log.info(
        "Device=%s  label=%s  category=%s  unit=%d  modbus=%d  web=%d",
        DEVICE_ID, DEVICE_LABEL, CATEGORY, UNIT_ID, PORT, WEB_PORT,
    )

    _store = build_store()

    # HTTP configuration portal
    try:
        web = await asyncio.start_server(http_handler, "0.0.0.0", WEB_PORT)
        asyncio.ensure_future(web.serve_forever())
        log.info("HTTP portal: http://0.0.0.0:%d/ (login: %s / %s)", WEB_PORT, WEB_USER, WEB_PASS)
    except OSError as exc:
        log.warning("Could not bind HTTP portal on port %d: %s", WEB_PORT, exc)

    # Register drift simulation
    asyncio.ensure_future(simulate(_store))

    # Modbus TCP server (blocks)
    context = ModbusServerContext(slaves={UNIT_ID: _store}, single=False)
    await StartAsyncTcpServer(context, address=("0.0.0.0", PORT))


if __name__ == "__main__":
    asyncio.run(main())
